I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 29, in script
    i "OIf you manage to defeat me in [Is-She-Kay Life]. You have 30 days to practice."
KeyError: u'Is-She-Kay Life'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 29, in script
    i "OIf you manage to defeat me in [Is-She-Kay Life]. You have 30 days to practice."
  File "C:\Users\Me\Desktop\renpy-7.3.2-sdk\renpy\ast.py", line 706, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\Me\Desktop\renpy-7.3.2-sdk\renpy\exports.py", line 1336, in say
    who(what, *args, **kwargs)
  File "C:\Users\Me\Desktop\renpy-7.3.2-sdk\renpy\character.py", line 1126, in __call__
    what = what_pattern.replace("[what]", sub(what, translate=True))
  File "C:\Users\Me\Desktop\renpy-7.3.2-sdk\renpy\character.py", line 1115, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\Me\Desktop\renpy-7.3.2-sdk\renpy\substitutions.py", line 253, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 585, in _vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 605, in get_value
KeyError: u'Is-She-Kay Life'

Windows-8-6.2.9200
Ren'Py 7.3.2.320
Graduating in 30 Days 1.0
Mon Aug 19 18:28:16 2019
